#!/usr/bin/env node
/**
 * Regenerates the FROZEN `node-sealed.vault.js` fixture (issue #150) by sealing
 * `fixtureDocument()` with the real `frontend/js/crypto.js`, under Node's WebCrypto.
 *
 * DO NOT run this to "fix" a failing parity test. The fixtures are frozen on purpose — a
 * failing parity test means something drifted, and regenerating would launder that drift into
 * the repo instead of catching it. Only run this deliberately, e.g. after an intentional,
 * documented, backward-compatible envelope change, and only alongside updating
 * `e2e/parity/README.md` to say so. See that README before running this at all.
 *
 * The fixture is emitted as a plain `.js` module (`export const nodeSealedFixture = {...}`),
 * not `.json`/`.mjs`: both vitest and Playwright need to load it with a plain `import`, and this
 * repo has no `"type": "module"`, so `.mjs` + `import.meta`-based fs reads collide with
 * Playwright's transform for `.js` specs (see ../README.md).
 *
 * Usage:  node e2e/parity/fixtures/generate.node.mjs
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createVault, DEFAULT_ITERATIONS } from '../../../frontend/js/crypto.js';
import { fixtureDocument, FIXTURE_PASSWORD, FIXTURE_RECOVERY_CODE } from './fixture-document.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function main() {
    const documentObj = fixtureDocument();
    const { vault, recoveryCode } = await createVault(documentObj, FIXTURE_PASSWORD, {
        recoveryCode: FIXTURE_RECOVERY_CODE,
        iterations: DEFAULT_ITERATIONS, // real KDF cost — the fixture must freeze a realistic envelope
    });

    const fixture = {
        _WARNING: 'TEST FIXTURE ONLY. Throwaway secrets, not real credentials. '
            + 'FROZEN — see e2e/parity/README.md before editing or regenerating this file.',
        sealedBy: 'node',
        nodeVersion: process.version,
        generatedAt: new Date().toISOString(),
        password: FIXTURE_PASSWORD,
        recoveryCode,
        document: documentObj,
        vault,
    };

    const header = '// FROZEN TEST FIXTURE (#150) — see ../README.md before editing or regenerating this file.\n'
        + '// Do NOT regenerate this to "fix" a failing parity test: that launders exactly the kind of\n'
        + '// envelope drift this test exists to catch. Only touch this deliberately (see the README).\n'
        + '//\n'
        + '// TEST FIXTURE ONLY: the password and recovery code below are throwaway secrets that exist\n'
        + '// only to seal this frozen vault. Never real credentials.\n'
        + '//\n'
        + '// Generated by generate.node.mjs — do not hand-edit.\n';
    const src = `${header}export const nodeSealedFixture = ${JSON.stringify(fixture, null, 4)};\n`;

    const out = path.join(__dirname, 'node-sealed.vault.js');
    writeFileSync(out, src, 'utf8');
    console.log('wrote', out);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
